export const cooldownCommands = [
    'bws', 'badgeweightsystem', 'badgeweight', 'badgeweightseed', 'badgerank',
    'compare', 'common',
    'firsts', 'firstplaceranks', 'fpr', 'fp', '#1s', 'first', '#1', '1s',
    'globals', 'osc', 'osustatscount',
    'leaderboard', 'maplb', 'mapleaderboard', 'ml',
    'lb',
    'map', 'm',
    'maprandom', 'f2', 'maprand', 'mapsuggest', 'randommap', 'randmap',
    'osu', 'profile', 'o', 'user', 'taiko', 'drums', 'fruits', 'ctb', 'catch', 'mania',
    'osuseet', 'setuser', 'set', 'setmode', 'setskin',
    'nochokes', 'nc',
    'osutop', 'top', 't', 'ot', 'toposu', 'topo',
    'taikotop', 'toptaiko', 'tt', 'topt',
    'ctbtop', 'fruitstop', 'catchtop', 'topctb', 'topfruits', 'topcatch', 'tctb', 'tf', 'topf', 'topc',
    'maniatop', 'topmania', 'tm', 'topm',
    'sotarks', 'sotarksosu', 'sotarkstaiko', 'taikosotarks', 'sotarkst', 'tsotarks',
    'sotarksfruits', 'fruitssotarks', 'fruitsotarks', 'sotarksfruit', 'sotarkscatch', 'catchsotarks', 'sotarksctb', 'ctbsotarks', 'fsotarks', 'sotarksf', 'csotarks', 'sotarksc',
    'sotarksmania', 'maniasotarks', 'sotarksm', 'msotarks',
    'pinned',
    'ppcalc', 'mapcalc', 'mapperf', 'maperf', 'mappp',
    'pp', 'rank',
    'ranking', 'rankings',
    'rs', 'recent', 'r',
    'rs best', 'recent best', 'rsbest', 'recentbest', 'rb',
    'recentlist', 'rl',
    'recentlisttaiko', 'rlt',
    'recentlistfruits', 'rlf', 'rlctb', 'rlc',
    'recentlistmania', 'rlm',
    'recenttaiko', 'rt',
    'recentfruits', 'rf', 'rctb',
    'recentmania', 'rm',
    'recentactivity', 'recentact', 'rsact',
    'saved',
    'scoreparse', 'score', 'sp',
    'scores', 'c',
    'scorestats', 'ss',
    'simplay', 'simulate', 'sim',
    'skin',
    'trackadd', 'track', 'ta', 'trackremove', 'trackrm', 'tr', 'untrack', 'trackchannel', 'tc', 'tracklist', 'tl',
    'userbeatmaps', 'ub', 'userb', 'ubm', 'um', 'usermaps',
    'whatif', 'wi',

    //non osu 
    'time', 'weather', 'tropicalweather', 'ts',

    'gif', 'hug', 'kiss', 'lick', 'pet', 'punch', 'slap',
    'image', 'imagesearch',
    'ytsearch', 'yt',
];