export const cooldownCommands = [
    'bests',
    'bws',
    'compare',
    'firsts',
    'globals',
    'map', 'm',
    'maplb', 'mapleaderboard', 'leaderboard',
    'nochokes', 'nc',
    'osu', 'o', 'profile', 'user',
    'osutop', 'top',
    'pinned',
    'recent', 'rs', 'r',
    'scoreparse', 'score', 'sp',
    'scores', 'c',
    'simulate', 'simplay',

    //non osu 
    'settings',
    'prefix',
    'convert',
    'help',
    'math',
    'remind',
    'time',

    'gif',
    'image', 'imagesearch',
    'ytsearch', 'yt',
];