type quoteTemplate = {
    string:string,
    names:number,
    verbs:number,
    descriptors:number,
}

export const templateStrings:quoteTemplate[] = [
    {
        string: 'Become the name1 who makes other name1s verb1',
        names: 1,
        verbs: 1,
        descriptors: 0,
    },
    {
        string: 'There are okay name1s and not-so-okay name1s',
        names: 1,
        verbs: 0,
        descriptors: 0,
    },
    {
        string: 'Forcing a name1 to be name2 is probably not as descriptor1 as it sounds',
        names: 2,
        verbs: 0,
        descriptors: 1,
    },
    {
        string: 'name1 is name2 on steroids',
        names: 2,
        verbs: 0,
        descriptors: 0,
    },
    {
        string: 'remember to always be descriptor1',
        names: 0,
        verbs: 0,
        descriptors: 1,
    },
    {
        string: 'Never let go of an opportunity to verb1',
        names: 0,
        verbs: 1,
        descriptors: 0,
    },
    {
        string: 'In order to acheive success, you must verb1',
        names: 0,
        verbs: 1,
        descriptors: 0,
    },
    {
        string: 'Always remember that you are a(n) descriptor1 name1',
        names: 1,
        verbs: 0,
        descriptors: 1,
    },
    {
        string: 'Seek name1, seek name2',
        names: 2,
        verbs: 0,
        descriptors: 0,
    },
    {
        string: 'you\'re descriptor1, but so is a name1',
        names: 1,
        verbs: 0,
        descriptors: 1,
    },
    {
        string: 'verb1 and verb2',
        names: 0,
        verbs: 2,
        descriptors: 0,
    },
    {
        string: 'keep calm and verb1',
        names: 0,
        verbs: 1,
        descriptors: 0,
    },
    {
        string: 'be the first to verb1 what any normal person would consider descriptor1',
        names: 0,
        verbs: 1,
        descriptors: 1,
    },
    {
        string: 'name1 begins when name2 ends',
        names: 2,
        verbs: 0,
        descriptors: 0,
    },
    {
        string: 'without verb1 there can be no name1',
        names: 1,
        verbs: 1,
        descriptors: 0,
    },
    {
        string: 'name1s begin when we learn to verb1',
        names: 1,
        verbs: 1,
        descriptors: 0,
    },
    {
        string: 'ensure that name1 feels descriptor1',
        names: 1,
        verbs: 0,
        descriptors: 1,
    },
    {
        string: 'you can be the reason why a name1 verb1',
        names: 1,
        verbs: 1,
        descriptors: 0,
    },
    {
        string: 'someone should verb1. You can be that someone',
        names: 0,
        verbs: 1,
        descriptors: 0,
    },
    {
        string: 'You carry the potential to become a descriptor1 name1',
        names: 1,
        verbs: 0,
        descriptors: 1,
    },
    {
        string: 'Don\'t verb1 with name1. verb2',
        names: 1,
        verbs: 2,
        descriptors: 0,
    },
    {
        string: 'you\'re descriptor1, but so is a name1',
        names: 1,
        verbs: 0,
        descriptors: 1,
    },
    {
        string: 'a name1 is never just a name2, but its not a name3',
        names: 3,
        verbs: 0,
        descriptors: 0,
    },
    {
        string: 'first comes name1, then comes name2',
        names: 2,
        verbs: 0,
        descriptors: 0,
    },
    {
        string: 'name1 is worth it. Thank you',
        names: 1,
        verbs: 0,
        descriptors: 0,
    },
    {
        string: 'Society without name1 is no fun.',
        names: 1,
        verbs: 0,
        descriptors: 0,
    },
] 

export const names:string[] = [
    'guy',
    'boy',
    'girl',
    'woman',
    'ball',
    'change',
    'angel',
    'book',
    'solutions',
    'problems',
    'cow',
    'dog',
    'colleague',
    'human being',
    'your wife',
    'your husband',
    'your partner',
    'your mother',
    'your father',
    'your brother',
    'your sister',
    'your sibling',
    'your cousin',
    'your aunt',
    'your uncle',
    'your niece',
    'your nephew',
    'your grandfather',
    'your grandmother',
    'your grandparent',
    'expert',
    'professional',
    'teacher',
    'electrician',
    'pilot',
    'hostess',
    'maid',
    'cat',
    'fungal infection',
    'mcdonald\'s',
    'success',
    'brain damage',
    'monkey',
    'bank',
    'a stranger',
    'the sunrise',
    'the sunset',
    'betrayal',
    'human sacrifice',
    'the planet',
    'the sun',
    'the earth',
    'the moon',
]

export const verbs:string[] = [
    'explode',
    'change',
    'evolve',
    'grow',
    'run away',
    'growl',
    'bark',
    'sob',
    'cry',
    'sleep',
    'woof',
    'get a sex change',
    'spy on people',
    'confuse random people',
    'try drugs',
    'regret everything',
    'cries',
    'ignore warnings',
    'panic',
    'attempt murder',
    'commit arson',
    'commit tax fraud',
    'relax',
    'remain calm',
    'hyperventilate'
]

export const descriptors:string[] = [
    'nice',
    'kind',
    'smelly',
    'bad',
    'good',
    'amazing',
    'slow',
    'fast',
    'moderately paced',
    'cow-shaped',
    'loud',
    'quiet',
    'talented',
    'stinky',
    'contagious',
    'outrageous',
    'angry',
    'trumpet sounding',
    'obese',
    'elongated',
    'spaghettified',
    'short',
    'tiny',
    'horny',
    'fuzzy',
    'furry',
    'intelligent',
    'incoherent',
    'inconspicuous',
    'embarrassed',
    'suspicious',
    'sour',
    'depressed',
    'sad',
    'bombastic',
    'undrinkable',
    'horrible',
    'dangerous',
    'insane',
    'ashamed'
]